version: "3.8"

services:
  db: #назввание сервиса
    image: postgres:13 #версия имеджа
    environment: #еввихи (тут в проекте env вообще не используется, что делать неправильно)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: #что нам надо запустить
      - postgres_data:/var/lib/postgresql/data
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh #скрипт для создания бд
    networks:
      - backend #в какой сети оно будет работаь 
    ports:
      - "5432:5432" #порты

  redis: #назввание сервиса (штука для кеширования)
    image: redis:6 #версия
    networks: #в какой сети оно будет работать
      - backend 

  auth-service: #назввание сервиса
    build: ./auth-service #папка билда
    ports:
      - "5000:5000" #порт на котором расположится
    environment: #енвишки (нигде не используются)
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=b_db_auth
      - JWT_SECRET=HiHiHaHa #!!!ИСПОЛЬЗУЕТСЯ ВЕЗДЕ. Для авторизации (секретный токен на основе которого генертся JWT-токены)
      - PORT=5000
    command: bash -c "npm run migration:run && npm run start" #скрипт, который запускает сначала миграции, а потом само приложение
    networks: #в какой сети оно будет работать
      - backend
    depends_on: #зависимости (выполнение произойдёт только после выполнения сервисов ниже)
      - db

  #далее всё тоже самое, что и в сервисе выше 

  events-service:
    build: ./events-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=b_db_events
      - JWT_SECRET=HiHiHaHa
      - PORT=5001
    command: bash -c "npm run migration:run && npm run start"
    networks:
      - backend
    depends_on:
      - db

  participants-service:
    build: ./participants-service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME="postgres
      - DB_PASSWORD="postgres
      - DB_NAME=b_db_participants
      - JWT_SECRET=HiHiHaHa
      - PORT=5002
    command: bash -c "npm run migration:run && npm run start"
    networks:
      - backend
    depends_on:
      - db

  user-service:
    build: ./user-service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=b_db_auth
      - JWT_SECRET=HiHiHaHa
      - PORT=5003
    command: bash -c "npm run migration:run && npm run start"
    networks:
      - backend
    depends_on:
      - db

volumes:
  postgres_data:

networks: #список сетей
  backend:
